### ISSUE TITLE
Error when creating lambda layer, size too large?

### ISSUE THREAD

**Issue by weisisheng** [jsreport/jsreport-aws-lambda-starter-kit#2]
A bit puzzled as decompressed, the folder is 234MB (below the 250MB limit) but the error message I get on AWS Console is "Failed to create layer version: Unzipped size must be smaller than 262144000 bytes".

Appreciate any insights.

**Comment by pofider** [comment]
Interesting. Do you install some extra packages? Or do you do something extra? I mean compared to what is mentioned in our tutorial https://jsreport.net/learn/aws-lambda-serverless

**Comment by weisisheng** [comment]
Not that I know of.  Just started studying the use case and was "sticking to the script".  What is the extracted folder size supposed to be please?

**Comment by pofider** [comment]
I tried to follow the tutorial and the layer was created without issues. I am on windows...

This command
`node createLambdaLayer.js`

Created 91.1MB layer.zip.
Which decompressed is something like 228MB

**Comment by pofider** [comment]
Ups, ok, I didn't run `npm start` and it seems this adds some more bytes and afterward I get the same error.
Give me some minutes, I add to the `createLambdaLayer.js` some more cleanup of files to decrease the size a bit.

**Comment by pofider** [comment]
I improved the cleanup, now you shouldn't have problems with the layer creation.
Please
```
git pull
npm i
node createLambdaLayer.js
```

**Comment by weisisheng** [comment]
All went smoothly, now for some more study then testing.  Thanks for the extraordinary support and quick response.

**Comment by weisisheng** [comment]
Just a brief FYI... I deleted all sample data except for invoice and am trying to add the report/blob storage for S3. The zipped file actually goes down to 90 MB but when i try to create the layer, I get the old warning back, "Failed to create layer version: Unzipped size must be smaller than 262144000 bytes".  Will study on how to reduce layers.

**Comment by umutc** [comment]
add this pattern to the cleanup function in the createLambdaLayer.js

`node_modules/**/*.map`, // Added to exclude all sourcemap files
